name: Prepare package
on: [push]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - run: echo "perform static code"
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Maven package
        run: mvn package -DskipTests
      - name: list compiled files
        run: ls -la target/
      - run: mv target/*.jar target/ecommerce.jar
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/ecommerce.jar



    
