name: Prepare package
on:
  push:
    tags:
     - "v*.*.*"
jobs:
  buildPackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Run the Maven package command
        run: mvn -DskipTests package
      - run: ls target/
      - run: mv target/*.jar app.jar
      - uses: ncipollo/release-action@v1
        with:
          name: My Release candidate
          artifacts: "target/*.jar"
          body: "my release of version: ${{github.ref}}"
