name: Run Unit tests
on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  CreatePackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Compile it
        run: mvn -DskipTests package
      - run: "ls -la target"
