name: Execute tests
on: [push]
jobs:
  PerformUnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Run the Mave
        run: mvn test
